### creating NUmpy Array

In [1]:
# 1. import Numpy as np
# 2. Create the following  array:
#   A 1D arrray of int from 1 to 10
#   B 2D array of shape(3,3) with values from 1 to 9
#   A Numpy array form list: [10 , 20 , 30, 40 ,50]
# 3.Print:
# Shape of each array
# Data type of each array


In [2]:
import numpy as np

# 1D array of integers from 1 to 10
arr1 = np.arange(1, 11)

# 2D array of shape (3,3) with values from 1 to 9
arr2 = np.arange(1, 10).reshape(3, 3)

# NumPy array from list
arr3 = np.array([10, 20, 30, 40, 50])

# Print arrays
print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

print("\nArray from List:")
print(arr3)

# Print shape and data type of each array
print("\n--- Array Information ---")

print("arr1 Shape:", arr1.shape)
print("arr1 Data Type:", arr1.dtype)

print("\narr2 Shape:", arr2.shape)
print("arr2 Data Type:", arr2.dtype)

print("\narr3 Shape:", arr3.shape)
print("arr3 Data Type:", arr3.dtype)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array from List:
[10 20 30 40 50]

--- Array Information ---
arr1 Shape: (10,)
arr1 Data Type: int32

arr2 Shape: (3, 3)
arr2 Data Type: int32

arr3 Shape: (5,)
arr3 Data Type: int32
