## Mathematical_Operations

In [3]:
import numpy as np

In [4]:
# astype()--> astype() will be helping us out with figuring out the data type of the column in the dataset in pandas and it will be used in numpy as well for getting the data type changed of our overall array

In [5]:
array = np.arange(1,10).reshape(3,3)

In [6]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# NumPy to convert the data type (dtype) of an array into float64.
new_array = array.astype('float64')

In [8]:
print(array)

print(type(new_array.dtype))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.dtype[float64]'>


### Mathematical Operation in numpy

In [9]:
### Scaler Operation ---> A scaler value will be multiplied with the array or a numeric value (eg. 1,4)

In [10]:
array1 = np.random.random((3,3)) * 100

In [11]:
array1

array([[35.51656491, 91.73037259,  1.17342118],
       [98.34858139, 62.89424672, 55.04004418],
       [39.2500213 , 41.86271565, 50.42572077]])

In [12]:
np.round(array1)

array([[36., 92.,  1.],
       [98., 63., 55.],
       [39., 42., 50.]])

In [13]:
# Scaler Operation with our Matrix or Array
array1 + 2

array([[ 37.51656491,  93.73037259,   3.17342118],
       [100.34858139,  64.89424672,  57.04004418],
       [ 41.2500213 ,  43.86271565,  52.42572077]])

In [14]:
a =5
b =6
print(a + b)

11


In [15]:
array - 5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [16]:
array * 5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
array/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [18]:
### We can apply scaler operation with the array in terms of arithmetic operation

In [19]:
a=5
b=6
a>b

False

In [20]:
new_A = array1.round() 


In [21]:
new_A > 60

array([[False,  True, False],
       [ True,  True, False],
       [False, False, False]])

In [22]:
# vector Operation --> Operation will be in btw the given number of matrices

In [23]:
arr_1 = np.arange(1,17).reshape(4,4)

In [24]:
arr_2 = np.arange(17,33).reshape(4,4)

In [25]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [27]:
arr_1 + arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [28]:
arr_2 - arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [29]:
arr_1*arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

### important functions in Numpy for Machine learning and data science

#### max() --> it is going to be used to calculate the max value inside a matrix or an array 
#### syntax for max() --> np.max(array)

In [30]:
max_val = np.max(arr_1)

In [31]:
max_val

16

In [32]:
array_data = np.round(np.random.random((4,4)) * 100).astype('int64')

In [33]:
array_data

array([[ 86,  14,  39,  10],
       [ 45,  21,  72,  44],
       [ 37, 100,   4,  11],
       [ 24,  97,  87,  17]], dtype=int64)

# axis ---> it provides us with the data about the any operation value inside a specific row or column or we can get a specific value row wise or column wise


#### axis = 0 --> column wise operation
#### axis = 1 --> row wise operation

In [34]:
np.max(array_data,axis = 0) ## max value
# column wise aswell

array([ 86, 100,  87,  44], dtype=int64)

In [35]:
np.max(array_data,axis = 1) ## max value
# row wise aswell

array([ 86,  72, 100,  97], dtype=int64)

In [36]:
# min() --> it will be used for calculating the minimum value from the matrix or array

In [37]:
array_data

array([[ 86,  14,  39,  10],
       [ 45,  21,  72,  44],
       [ 37, 100,   4,  11],
       [ 24,  97,  87,  17]], dtype=int64)

In [38]:
np.min(array_data)

4

In [39]:
np.min(array_data,axis = 1)

array([10, 21,  4, 17], dtype=int64)

In [40]:
np.min(array_data,axis = 0)

array([24, 14,  4, 10], dtype=int64)

In [41]:
array = np.arange(1,10)

In [42]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.max(array)

9

In [44]:
np.min(array)

1

In [45]:
# sum() ---> calculates the sum of all of the value of a given matrix

In [46]:
array_data

array([[ 86,  14,  39,  10],
       [ 45,  21,  72,  44],
       [ 37, 100,   4,  11],
       [ 24,  97,  87,  17]], dtype=int64)

In [47]:
np.sum(array_data)

708

In [48]:
np.sum(array_data, axis = 0)

array([192, 232, 202,  82], dtype=int64)

In [49]:
np.sum(array_data, axis = 1)

array([149, 182, 152, 225], dtype=int64)

In [50]:
## prod() ---> it helps with calculating the product of all values inside the matrix

In [51]:
np.prod(array)

362880

In [52]:
np.prod(array_data, axis = 1) # row wise product


array([ 469560, 2993760,  162800, 3443112], dtype=int64)

In [53]:
np.prod(array_data, axis = 0) # column wise product


array([3436560, 2851800,  977184,   82280], dtype=int64)

# Statistical function in Numpy

In [54]:
## mean() ---> systax for mean() --> np.mean() --> mean of all values inside the array or matrix

In [55]:
array_data

array([[ 86,  14,  39,  10],
       [ 45,  21,  72,  44],
       [ 37, 100,   4,  11],
       [ 24,  97,  87,  17]], dtype=int64)

In [56]:
np.mean(array_data,axis = 1)

array([37.25, 45.5 , 38.  , 56.25])

In [57]:
np.mean(array_data,axis = 0)

array([48. , 58. , 50.5, 20.5])

In [58]:
## std() --> it provides with the standard deviation of all values of the matrix or array

In [59]:
array_data

array([[ 86,  14,  39,  10],
       [ 45,  21,  72,  44],
       [ 37, 100,   4,  11],
       [ 24,  97,  87,  17]], dtype=int64)

In [60]:
np.std(array_data)

32.42202183701689

In [61]:
# median() --> to calculate median of all values in the array or matrix
# syntax for median ---> np.median()

In [62]:
array_data

array([[ 86,  14,  39,  10],
       [ 45,  21,  72,  44],
       [ 37, 100,   4,  11],
       [ 24,  97,  87,  17]], dtype=int64)

In [63]:
np.median(array_data)

38.0

In [64]:
np.median(array_data,axis=0)

array([41. , 59. , 55.5, 14. ])

In [65]:
np.median(array_data,axis = 1)

array([26.5, 44.5, 24. , 55.5])

In [66]:
# var --> it helps with calculating the varience of all values inside the array or matrix
# syntax ---> np.var()

In [67]:
np.var(array_data)

1051.1875

## Trigonometric Function

In [68]:
# sin() --> sin value for the value we are going to pass inside it

In [69]:
np.sin(0)

0.0

In [70]:
np.sin(60)

-0.3048106211022167

In [71]:
np.tan(45)

1.6197751905438615

In [72]:
np.cos(12)

0.8438539587324921

In [73]:
### DOT Products of Matrices
## Syntax for Dot Product --> np.dot(matrix1,matrix2)

In [78]:
matrix_1 = np.round(np.random.random((3,4)) * 100).astype('int64')
matrix_2 = np.round(np.random.random((4,3)) * 100).astype('int64')

In [75]:
matrix_1

array([[ 94,  63,   1,  54],
       [ 90,  66,  13,  75],
       [ 77, 100,  19,  84]], dtype=int64)

In [76]:
matrix_2

array([[11,  1, 13, 90],
       [36, 41, 45, 66],
       [24, 54, 70,  1]], dtype=int64)

In [79]:
np.dot(matrix_1,matrix_2)

array([[15909, 10209,  5715],
       [ 6506,  4860,  3674],
       [11551,  7348,  6513]], dtype=int64)

In [80]:
## log()---> to calculate the  log of all values of our matrix


In [82]:
np.log(matrix_1)

array([[4.18965474, 4.53259949, 4.14313473, 2.89037176],
       [3.25809654, 2.63905733, 4.35670883, 2.77258872],
       [4.09434456, 4.00733319, 3.80666249, 3.66356165]])

In [83]:
# exp() --> exponential of all values inside the matrix

In [84]:
np.exp(matrix_1)

array([[4.60718663e+28, 2.45124554e+40, 2.29378316e+27, 6.56599691e+07],
       [1.95729609e+11, 1.20260428e+06, 7.49841700e+33, 8.88611052e+06],
       [1.14200739e+26, 7.69478527e+23, 3.49342711e+19, 8.65934004e+16]])

In [85]:
np.exp(matrix_2)

array([[4.09399696e+35, 8.65934004e+16, 6.56599691e+07],
       [8.22301271e+36, 7.69478527e+23, 6.56599691e+07],
       [2.35385267e+17, 3.18559318e+16, 1.78482301e+08],
       [5.45981500e+01, 1.09663316e+03, 9.01762841e+39]])

In [96]:
## round()---> it helps with rounding off the float values to its nearest possible integer value

In [97]:
array = np.random.random((3,4))

In [102]:
array = array*10
array

array([[203.08568672, 272.90414992,  66.74492688,  73.12188124],
       [129.62900177, 590.99806345, 454.98109826, 354.7821495 ],
       [628.50104583, 584.25756965, 218.74048734, 407.58054803]])

In [103]:

np.round(array)

array([[203., 273.,  67.,  73.],
       [130., 591., 455., 355.],
       [629., 584., 219., 408.]])

In [104]:
# celi() ---> Next corresponding value -----> np.ceil()

In [105]:
array

array([[203.08568672, 272.90414992,  66.74492688,  73.12188124],
       [129.62900177, 590.99806345, 454.98109826, 354.7821495 ],
       [628.50104583, 584.25756965, 218.74048734, 407.58054803]])

In [106]:
# floor() --> It can provide us with the previous value

In [107]:
np.floor(array)

array([[203., 272.,  66.,  73.],
       [129., 590., 454., 354.],
       [628., 584., 218., 407.]])

In [109]:
# Transpose() --->  It calculate the transpose of the given matrix
# Transpose syntax ---> np.transpose(arr) or arr.T

# transpose ---> (i,j) ---> (j,i) ---> (3,4) ----> T ----> (4,3)

In [110]:
array = np.arange(1,13).reshape(3,4)

In [111]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [113]:

np.transpose(array)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [114]:
## Ravel() --> Ravel() --> np.ravel() -->convert nd array into 1d array 

In [115]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
array.ndim

2

In [117]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Indexing and slicing process in numpy

In [118]:
# Indexing ---> lists[,size-1] ---> to have that acces over the value

In [119]:
array = np.round(np.random.random((5,5)) * 100).astype('int64')

In [120]:
array

array([[30, 77, 44, 93, 56],
       [ 5, 12,  4, 71, 84],
       [95, 99, 75, 58, 17],
       [63, 92,  1, 49, 22],
       [60, 68, 62, 72, 85]], dtype=int64)

In [123]:
array_one=np.arange(1,10)

In [124]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
array_one[6]

7

In [127]:
array_one[8]

9

In [128]:
array

array([[30, 77, 44, 93, 56],
       [ 5, 12,  4, 71, 84],
       [95, 99, 75, 58, 17],
       [63, 92,  1, 49, 22],
       [60, 68, 62, 72, 85]], dtype=int64)

In [129]:
array[4,4]

85

In [130]:
array[2,3]

58

In [136]:
array_three = np.arange(1,9).reshape(2,2,2)

In [137]:
array_three[1,0,1]

6

In [138]:
array_three[0,1,0]

3

In [139]:
# Slicing --> Similer approach just like the lsit [:]

In [140]:
array[:,2]

array([44,  4, 75,  1, 62], dtype=int64)

In [141]:
array[0,:]

array([30, 77, 44, 93, 56], dtype=int64)

In [142]:
array

array([[30, 77, 44, 93, 56],
       [ 5, 12,  4, 71, 84],
       [95, 99, 75, 58, 17],
       [63, 92,  1, 49, 22],
       [60, 68, 62, 72, 85]], dtype=int64)

In [143]:
array[2:4,3:5]

array([[58, 17],
       [49, 22]], dtype=int64)

In [144]:
array[2:, 1:4]

array([[99, 75, 58],
       [92,  1, 49],
       [68, 62, 72]], dtype=int64)

In [145]:
# Iterating over an array

In [146]:
array = np.arange(1,10)

In [147]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [148]:
array = np.arange(1,17).reshape(4,4)

In [149]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [150]:
for i in array:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [152]:
array = np.arange(1,28).reshape(3,3,3)

In [153]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [154]:
for i in array:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [155]:
### nditer()---> it can help us out with iterating over every value in a nd array

In [156]:
for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [157]:
# 1D array ---> value by value on iteration
# 2D array ---> Row by row on Iteration
# 3D array ---> 2d array by 2D array

## Stacking and Spliting

##### Stacking means joining multiple arrays together.

##### Splitting means dividing an array into smaller arrays.

##### size of the array must be the same

In [158]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [159]:
result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


In [160]:
# Hstacking---> Row by row joining is done
# Vstacking---> Column by column joining is done

In [161]:
array_two = np.arange(13,25).reshape(3,4)

In [162]:
array_two

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [167]:
h_array = np.hstack((array1,array_two))

In [168]:
h_array

array([[35.51656491, 91.73037259,  1.17342118, 13.        , 14.        ,
        15.        , 16.        ],
       [98.34858139, 62.89424672, 55.04004418, 17.        , 18.        ,
        19.        , 20.        ],
       [39.2500213 , 41.86271565, 50.42572077, 21.        , 22.        ,
        23.        , 24.        ]])

In [172]:
v_array = np.vstack((array,array_two))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
## Horizontal split ---> np.hsplit(array,number)
## vertical split ---> np.vsplit(array,number of parts)


In [171]:
np.hsplit(v_array,2)

NameError: name 'v_array' is not defined