## Numpy 

###### Numpy is a fundamental package for sciencetific computing  in python . It is a Python library that provides a multi dimentional array object and various derived object such as masked arrays or matrics and an assortment of routing for fast operation on array including mathematical , logical , shape manipulation , sorting, selecting , I/O , discrete fourier transform , basic linear algebra , stastical operation , Random simulation, etc.


##### at the core of the numpy package is the n dimensional array object.


### why Numpy?
#### 2008-2009, data science ---> Matlab , R language 

### Data types in python ---> list , dictionary ---> slow
syntax --> Python --> Easy
## we needed speed and less memory to work with the huge amount of data
Numpy --> c language --> wrapped ---> python Language
## Numpy --> syntax --> Easy for beginners--> performing scientic calculations --> creating multi dimentional arrays --> speeds is faster for applying operations --> Less memory




### Libraries like scikit learn, tensorflow and pytorch require input data in numpy array or tensors.


### Numpy Arrays Vs Python Sequence
#### Numpy arrays have a fixed size at creating , unlike python lists which grow dynamically chaning the size of an n dimentional array will create a new array and delete the original.



#### The elements in a Numpy array are required to be of the same data type and thus will be of the same size in memory.



#### Numpy array facilitate advanced math and other types of operation on larger number of data . Typically , such operation are executed more efficiently with less code than is possible using python's built in sequences.

# Numpy important formulas

In [2]:
# able to create to multi dientional array 
import numpy as np

numpy_array = np.array([1,2,3,4])
numpy_array

array([1, 2, 3, 4])

In [3]:
type(numpy_array)

numpy.ndarray

In [4]:
numpy_array_2d = np.array([[1,2,3] , [3,4,5]])

In [5]:
numpy_array_2d

array([[1, 2, 3],
       [3, 4, 5]])

# np.array() --> creating multi dimention array

#### dtype parameter --> which can help us out with deciding about the size of the data we are going to store inside our array


In [6]:
np.array([1,2,3,4,5] , dtype=np.int32)
# It tells NumPy what type of values to store inside the array

array([1, 2, 3, 4, 5])

In [7]:
np.array([7,8,9,10,11] , dtype=np.int64)

array([ 7,  8,  9, 10, 11], dtype=int64)

In [8]:
# np.float64 np.float32

In [9]:
np.array([1,2,3,4,5] , dtype=bool) 

array([ True,  True,  True,  True,  True])

In [10]:
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [11]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
arrange_data=np.arange(1,17)
# arrange_data.reshape(4,4)
arrange_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

## np.reshape()--> It helps us out with changing the shape of the array as per our needs


In [15]:
arrange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
# ones()

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## random() --> it helps us out with generating any random values from 0 to 1 inside our matrix

In [19]:
np.random.random((3,4))

array([[0.01688405, 0.98779984, 0.45068226, 0.3094801 ],
       [0.67073085, 0.92927633, 0.59069351, 0.20922651],
       [0.90216145, 0.37966558, 0.2214921 , 0.60160945]])

In [20]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Indentity matrix:- It helps us out with creating the matrix as an Identity matrix (SQuare Matrix-> Row = Column)

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# linspace()--> It makes sure that every value with a given range is going to have similer distance from each other 

In [25]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## Attributes

##### ndim -> ndim stands for n dimentions

In [26]:
arr = np.array([1,2,3])


In [27]:
arr

array([1, 2, 3])

In [28]:
arr.ndim

1

In [ ]:
array1 = np.array([[[1,2],[3,4],[5,6]]])


3

In [31]:
array1.ndim

3

In [32]:
# shape--> It provides us with the idea about the rows, column in data set or array

In [33]:
Array = np.array([[1,3,5] , [2,4,6] , [11,15,13]])


In [34]:
Array

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [11, 15, 13]])

In [35]:
Array.shape

(3, 3)

In [36]:
ThreeDArray = np.array([[[1,2],[3,4]] , [[1,2] , [3,4]] ,])

In [37]:
ThreeDArray.shape

(2, 2, 2)

In [38]:
# Size ---> Total number of Elements present inside our data set or array

In [40]:
array_element = np.arange(5,57)


In [41]:
array_element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56])

In [42]:
array_element.size

52

In [47]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr.itemsize)
print(arr.dtype)

4
int32


In [48]:
arr = np.array([[1,2],[3,4],[5,6]] , dtype=np.int64)
print(arr.itemsize)
print(arr.dtype)

8
int64


### int32 = 32 bits
### 1 byte = 8 bits
### int64 = 64 bits = 8 bytes.

In [49]:
# itemsize---> provides with the idea about the size of unique element inside our array in bytes

In [50]:
# dtype --> it provides us with the idea about the type of every items inside of array

In [51]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int32')

In [ ]:
# It gives dtype('int32') because NumPy automatically chooses a data type (dtype) that can store the values efficiently.